# Generated by Django 3.1.7 on 2021-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('client', 'client')], max_length=16, null=True),
        ),
    ]
